stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  ENVIRONMENT: "test"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "building job start..."
    - sudo ~/script/build.sh

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - sudo ~/script/deploy.sh
    - echo "Application successfully deployed."
  