spring:
  #session失效时间(分钟)
  session:
    timeout: 43776
    store-type: redis
  #redis
  redis:
    port: 6379
    host: 139.224.101.197
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
      routes:
        - id: sql-practice-user-service
          uri: lb://sql-practice-user-service
          predicates:
            - Path=/api/user/**
        - id: sql-practice-question-service
          uri: lb://sql-practice-question-service
          predicates:
            - Path=/api/question/**
        - id: sql-practice-judge-service
          uri: lb://sql-practice-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: sql-practice-gateway
  main:
    web-application-type: reactive
server:
  port: 8100

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2