spring:
  #session失效时间(分钟)
  session:
    timeout: 43776
    store-type: redis
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #redis
  redis:
    port: 6379
    host: 139.224.101.197
    database: 0
  jackson:
    date-format: yyyy-MM-dd
    timeZone: Asia/Shanghai