server:
  servlet:
    context-path: /api/study
    session:
      cookie:
        path: /api
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    persist-authorization: true
knife4j:
  enable: true
