spring:
  application:
    name: sql-practice-question-service

  #session失效时间(分钟)
  session:
    timeout: 4377600
    store-type: redis
  #redis
  redis:
    port: 6379
    host: 139.224.101.197
    database: 0
  jackson:
    date-format: yyyy-MM-dd
    timeZone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Dbase2122.
    url: jdbc:mysql://139.224.101.197:3306/sql_practice?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
rocketmq:
  name-server: 139.224.101.197:9876
  producer:
    group: producer
    send-message-timeout: 30000
server:
  port: 8103
  servlet:
    context-path: /api/question
    session:
      cookie:
        path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    persist-authorization: true
knife4j:
  enable: true